version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "UTC"
    volumes:
      - datadb:/var/lib/mysql

  pma:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_PORT=80
    ports:
      - '5050:80'
    depends_on:
      - db

  backend:
      build: ./app
      container_name: backend
      restart: always
      ports:
      - '5000:5000'       
      environment:
      - TZ=UTC  
      depends_on:
      - db

volumes:
  datadb:
  backend_data: